### PR TITLE
Adds search functionality to watchlist

### PR DESCRIPTION
**Pull request by BadgerCode**
# Watchlist search functionality
* Allows admin to search the watchlist by Steam ID, player name, admin name and reason
* Preview video - https://youtu.be/ztkYmyEz4Ck

# Watchlist join message
This change also prints out the reason why a player is on the watchlist when they join
preview

I opened this PR a bit too early, so I still need to test it some more.

### CODE REVIEW

**Comment by kralicky** [comment]
Thank you for contributing!

**Comment by kralicky** [comment]
Oops didn't see that you want to test it some more. Let me know when it's ready and I will merge.

**Comment by BadgerCode** [comment]
Hey this should be good to go now!

I'm not sure what's the best way to get these changes in now.
Maybe a "revert revert" PR, or undo the "revert" commit on master.

**Comment by kralicky** [comment]
I'll revert the revert, haha. thanks again.

**Pull request merged**
